Cli homework done
smirnov-i-SPbAU/SoftwareDesign pull request #1
Opened 2020-01-30 17:26 UTC by smirnov-i-SPbAU

2020-02-10 13:00 UTC, yurii-litvinov requested changes
В целом всё правильно, но Windows требует несколько большего внимания.

2020-02-10 13:00 UTC, yurii-litvinov commented on HA01_CLI/src/main/kotlin/ru/spbau/smirnov/cli/Environment.kt
> +     * variables to a new process
Можно было это как-то инкапсулировать тем не менее. Например, принимать ProcessBuilder сюда и заполнять его переменными окружения тут.

2020-02-10 13:00 UTC, yurii-litvinov commented on HA01_CLI/src/main/kotlin/ru/spbau/smirnov/cli/Shell.kt
> +    private var lastReturnCode = 0
Кажется, нигде не используется. На будущее, может, пригодится, но лучше не делать заранее на будущее, а делать так, чтобы в будущем, если оно таки наступит, было легко это сделать. Например, оставить, что Executor.execute возвращает код возврата, просто не сохранять его и не использовать нигде.

2020-02-10 13:00 UTC, yurii-litvinov commented on HA01_CLI/src/main/kotlin/ru/spbau/smirnov/cli/commands/Assignment.kt
> +    override fun equals(other: Any?): Boolean {
А зачем командам оператор сравнения?

2020-02-10 13:00 UTC, yurii-litvinov commented on HA01_CLI/src/main/kotlin/ru/spbau/smirnov/cli/commands/Wc.kt
> +        val newlines = string.count { it.toString() == System.lineSeparator() }
Не совсем. "Настоящий" wc считает количество строк, то есть если переносов строк не было, получается 1, у Вас 0.

2020-02-10 13:00 UTC, yurii-litvinov commented on HA01_CLI/src/main/kotlin/ru/spbau/smirnov/cli/preprocessing/substitution/Tokens.kt
> +}
А в Котлине, насколько я помню, ведь есть sealed class-ы --- что-то вроде discriminated union-ов функциональных языков. Если токен может быть только либо таким, либо другим, то, может, тут имеет смысл этим попользоваться. То же, может быть, применимо к состояниям автомата для лексического анализа.

2020-02-10 13:00 UTC, yurii-litvinov commented on HA01_CLI/src/test/kotlin/ru/spbau/smirnov/cli/commands/CatTest.kt
> +            "some\ncontent\nis\nhere\n42\n",
Не работает под виндой из-за переносов строк. Используйте System.lineSeparator. И я б ещё рекомендовал сделать билд под виндой на Travis, чтобы исключить такие проблемы

2020-02-10 13:00 UTC, yurii-litvinov commented on HA01_CLI/src/main/kotlin/ru/spbau/smirnov/cli/commands/Wc.kt
> +        val newlines = string.count { it.toString() == System.lineSeparator() }
К тому же, под виндой всё равно не работает: 
```
> wc build.gradle
0 102 1181 build.gradle
```

2020-02-10 13:05 UTC, smirnov-i-SPbAU commented on HA01_CLI/src/test/kotlin/ru/spbau/smirnov/cli/commands/CatTest.kt
> +            "some\ncontent\nis\nhere\n42\n",
Travis не умеет в джаву под виндой :(

2020-02-10 13:15 UTC, smirnov-i-SPbAU commented on HA01_CLI/src/main/kotlin/ru/spbau/smirnov/cli/commands/Assignment.kt
> +    override fun equals(other: Any?): Boolean {
Для тестирования парсера. Там я проверяю, что он создаёт нужные команды с нужными аргументами

2020-02-10 13:23 UTC, yurii-litvinov commented on HA01_CLI/src/test/kotlin/ru/spbau/smirnov/cli/commands/CatTest.kt
> +            "some\ncontent\nis\nhere\n42\n",
Его можно убедить. Не указываете language (или пишете language: shell), ставите JDK и все нужные тулы через Chocolatey (на travis он предустановлен), запускаете из скрипта. Если неохота с этим мучиться, есть специально заточенная под Windows CI --- https://www.appveyor.com/, там есть шанс, что билд для Java заработает без усилий.

2020-02-10 13:24 UTC, yurii-litvinov commented on HA01_CLI/src/main/kotlin/ru/spbau/smirnov/cli/commands/Assignment.kt
> +    override fun equals(other: Any?): Boolean {
А, тогда ок. Я бы мог сказать, что незорошо код для поддержки тестов писать в "боевом" коде, но для equals можно сделать исключение.

2020-02-10 16:08 UTC, smirnov-i-SPbAU commented on HA01_CLI/src/main/kotlin/ru/spbau/smirnov/cli/commands/Wc.kt
> +        val newlines = string.count { it.toString() == System.lineSeparator() }
[Вики](https://en.wikipedia.org/wiki/Wc_(Unix)) и ман говорят, что wc считает именно количество переносов. И мой вывод совпадает с выводом "настоящего" wc.
Винду исправлю

2020-03-10 10:41 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2020-03-19 17:38 UTC, merged